import { fileURLToPath } from 'node:url';
import { mkdirSync } from 'node:fs';
import { beforeAll, describe, expect, it } from 'vitest';
import { DEFAULT_REPORT_OPTIONS, buildReportHtml } from '../export';
import { SCENARIOS, scenarioBackup } from '../__fixtures__/scenarios';

/**
 * Golden test for the 10 report scenarios. Each scenario is rendered through the pure
 * `buildReportHtml` and its output — both the HTML and a `Backup`-shaped JSON — is pinned with
 * `toMatchFileSnapshot`. The committed files under `__fixtures__/reports/` double as the
 * human-reviewable sample reports (open `index.html`) and as a drift guard: any unintended change
 * to the report renderer or the fixtures fails this test. Regenerate with `vitest -u`.
 */
const REPORTS_DIR = fileURLToPath(new URL('../__fixtures__/reports/', import.meta.url));

function reportPath(name: string, ext: string): string {
  return fileURLToPath(new URL(`../__fixtures__/reports/${name}.${ext}`, import.meta.url));
}

function renderScenario(scenario: (typeof SCENARIOS)[number]): string {
  return buildReportHtml(
    scenario.profile,
    scenario.doses,
    scenario.entries,
    scenario.rangeStart,
    scenario.rangeEnd,
    scenario.options ?? DEFAULT_REPORT_OPTIONS,
  );
}

beforeAll(() => {
  mkdirSync(REPORTS_DIR, { recursive: true });
});

describe('golden report scenarios', () => {
  it.each(SCENARIOS.map((scenario) => [scenario.name, scenario] as const))(
    'renders a stable report for %s',
    async (name, scenario) => {
      await expect(renderScenario(scenario)).toMatchFileSnapshot(reportPath(name, 'html'));
    },
  );

  it.each(SCENARIOS.map((scenario) => [scenario.name, scenario] as const))(
    'exports a stable backup for %s',
    async (name, scenario) => {
      const json = `${JSON.stringify(scenarioBackup(scenario), null, 2)}\n`;
      await expect(json).toMatchFileSnapshot(reportPath(name, 'backup.json'));
    },
  );

  it('builds a gallery index of every scenario', async () => {
    const cards = SCENARIOS.map(
      (scenario) => `    <section class="card">
      <h2>${scenario.title}</h2>
      <p class="summary">${scenario.summary}</p>
      <p class="links"><a href="./${scenario.name}.html">Open report</a> · <a href="./${scenario.name}.backup.json">Backup JSON</a></p>
      <iframe src="./${scenario.name}.html" title="${scenario.title}"></iframe>
    </section>`,
    ).join('\n');
    const index = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>ADHD-log — golden provider reports</title>
    <style>
      body { font-family: -apple-system, sans-serif; margin: 0; padding: 24px; background: #f5f0e8; color: #2b2622; }
      h1 { margin: 0 0 4px; }
      .intro { color: #6b6258; max-width: 60ch; }
      .card { margin: 28px 0; padding: 16px; background: #fff; border: 1px solid #ddd3c4; border-radius: 8px; }
      .card h2 { margin: 0 0 6px; color: #2f6d4f; }
      .summary { margin: 0 0 8px; color: #6b6258; }
      .links { margin: 0 0 12px; font-size: 14px; }
      iframe { width: 100%; height: 520px; border: 1px solid #ddd3c4; border-radius: 6px; background: #fff; }
    </style>
  </head>
  <body>
    <h1>Golden provider reports</h1>
    <p class="intro">Ten deterministic, clinically-grounded sample datasets, each rendered through the app's <code>buildReportHtml</code>. Generated by <code>lib/__tests__/scenarios.test.ts</code> — not medical advice.</p>
${cards}
  </body>
</html>
`;
    await expect(index).toMatchFileSnapshot(reportPath('index', 'html'));
  });
});
